---
name: Kubernetes 1.23 OS disk - KVM
version: 1.23.6-6.2.0-1.20220428
publisher: OpenNebula Systems
description: |-
  Beta release.

  OS disk for the Kubernetes/Ubuntu appliance.
short_description: OS disk of the Kubernets/Ubuntu appliance
tags:
- disk
- kubernetes
- service
format: qcow2
creation_time: 1651140000
os-id: none
os-arch: all
hypervisor: KVM
opennebula_version: >-
  5.13, 6.0, 6.1, 6.2, 6.3, 6.4
images:
- name: kubernetes_ubuntu
  url: >-
    https://d24fmfybwxpuhu.cloudfront.net/service_kubernetes_ubuntu-6.2.0-1.20220428.qcow2
  type: OS
  dev_prefix: vd
  driver: qcow2
  size: 21474836480
  checksum:
    md5: 7e53fb2122e779cd1c946db81dc07743
    sha256: 372544c64c241fc3b29e588c2884e3cdddb757c5b18dfad8c930535e6b171e90
