---
name: Kubernetes 1.23 OS disk
version: 1.23.7-6.4.0-1.20220614
publisher: OpenNebula Systems
description: |-
  Beta release.

  OS disk for the Kubernetes 1.23 appliance.

  Please refer to the [documentation](https://docs.opennebula.io/appliances/service/kubernetes_service.html).
short_description: OS disk for the Kubernets 1.23 appliance
tags:
- disk
- kubernetes
- service
format: qcow2
creation_time: 1651140000
os-id: none
os-arch: all
hypervisor: ALL
opennebula_version: >-
  6.2, 6.3, 6.4
images:
- name: kubernetes_ubuntu
  url: https://d24fmfybwxpuhu.cloudfront.net/service_kubernetes_ubuntu-6.4.0-1.20220614.qcow2
  type: OS
  dev_prefix: vd
  driver: qcow2
  size: 21474836480
  checksum:
    md5: 89bf609132610100311890d55c0fb9e9
    sha256: 373c8c43004d73e72f90838fe4a07b4efc221de9e49eb1ba44a699a35aa4c96b
