---
name: Kubernetes 1.23 OS disk
version: 1.23.6-6.4.0-1.20220506
publisher: OpenNebula Systems
description: |-
  Beta release.

  OS disk for the Kubernetes 1.23 appliance.

  Please refer to the [documentation](https://docs.opennebula.io/appliances/service/kubernetes_service.html).
short_description: OS disk for the Kubernets 1.23 appliance
tags:
- disk
- kubernetes
- service
format: qcow2
creation_time: 1651140000
os-id: none
os-arch: all
hypervisor: ALL
opennebula_version: >-
  6.2, 6.3, 6.4
images:
- name: kubernetes_ubuntu
  url: >-
    https://d24fmfybwxpuhu.cloudfront.net/service_kubernetes_ubuntu-6.4.0-1.20220506.qcow2
  type: OS
  dev_prefix: vd
  driver: qcow2
  size: 21474836480
  checksum:
    md5: 1ebfd84faff42f5de18431c27d6b810f
    sha256: 2bb7bbbb6e8732a03d824139c6dc0c61ec1f672cc2f895d15ea981f2c19d7114
