---
name: Kubernetes 1.23 OS disk
version: 1.23.7-6.4.0-1.20220609
publisher: OpenNebula Systems
description: |-
  Beta release.

  OS disk for the Kubernetes 1.23 appliance.

  Please refer to the [documentation](https://docs.opennebula.io/appliances/service/kubernetes_service.html).
short_description: OS disk for the Kubernets 1.23 appliance
tags:
- disk
- kubernetes
- service
format: qcow2
creation_time: 1651140000
os-id: none
os-arch: all
hypervisor: ALL
opennebula_version: >-
  6.2, 6.3, 6.4
images:
- name: kubernetes_ubuntu
  url: https://d24fmfybwxpuhu.cloudfront.net/service_kubernetes_ubuntu-6.4.0-1.20220609.qcow2
  type: OS
  dev_prefix: vd
  driver: qcow2
  size: 21474836480
  checksum:
    md5: 65beabc4c4bac7ab4954d0d2002d19ff
    sha256: 6a36d5a3eded6e3c8ccc08c19ef0abd2bae812d38e7c400704297acfd3699769
