---
name: Kubernetes 1.23 VNF
version: 1.23.6-6.4.0-1.20220509
publisher: OpenNebula Systems
description: |-
  Beta release.

  Appliance providing several Virtual Network Functions (routing, NAT, DNS,
  DHCP) to run as regular **Virtual Machine**. See the dedicated
  [documentation](https://docs.opennebula.io/appliances/service/vnf.html).
short_description: Appliance with several Virtual Network Functions to run
  as VM
tags:
- alpine
- kubernetes
- service
- vnf
format: qcow2
creation_time: 1651140000
os-id: Alpine
os-release: "3.14"
os-arch: x86_64
hypervisor: ALL
opennebula_version: >-
  6.2, 6.3, 6.4
opennebula_template:
  context:
    network: "YES"
    oneapp_vnf_dhcp4_enabled: "NO"
    oneapp_vnf_dns_enabled: "$ONEAPP_VNF_DNS_ENABLED"
    oneapp_vnf_dns_interfaces: "$ONEAPP_VNF_DNS_INTERFACES"
    oneapp_vnf_dns_max_cache_ttl: "$ONEAPP_VNF_DNS_MAX_CACHE_TTL"
    oneapp_vnf_dns_use_rootservers: "$ONEAPP_VNF_DNS_USE_ROOTSERVERS"
    oneapp_vnf_keepalived_enabled: "YES"
    oneapp_vnf_keepalived_vrid: ""
    oneapp_vnf_lb0_ip: "$ONEAPP_VNF_LB0_IP"
    oneapp_vnf_lb0_port: "$ONEAPP_VNF_LB0_PORT"
    oneapp_vnf_lb0_method: "dr"
    oneapp_vnf_lb0_protocol: "tcp"
    oneapp_vnf_lb0_scheduler: ""
    oneapp_vnf_lb_enabled: "YES"
    oneapp_vnf_lb_onegate_enabled: "YES"
    oneapp_vnf_lb_refresh_rate: "$ONEAPP_VNF_LB_REFRESH_RATE"
    oneapp_vnf_nat4_enabled: "$ONEAPP_VNF_NAT4_ENABLED"
    oneapp_vnf_nat4_interfaces_out: "$ONEAPP_VNF_NAT4_INTERFACES_OUT"
    oneapp_vnf_router4_enabled: "$ONEAPP_VNF_ROUTER4_ENABLED"
    oneapp_vnf_router4_interfaces: "$ONEAPP_VNF_ROUTER4_INTERFACES"
    oneapp_vrouter_eth0_vip0: "$ONEAPP_VNF_LB0_IP"
    oneapp_vrouter_eth1_vip0: "$ONEAPP_VROUTER_ETH1_VIP0"
    report_ready: "YES"
    ssh_public_key: "$USER[SSH_PUBLIC_KEY]"
    token: "YES"
  cpu: "1"
  graphics:
    listen: "0.0.0.0"
    type: vnc
  inputs_order: ""
  memory: "512"
  nic_default:
    model: virtio
  lxd_security_privileged: "true"
  os:
    arch: x86_64
  user_inputs: {}
logo: router.png
images:
- name: kubernetes_vnf
  url: >-
    https://d24fmfybwxpuhu.cloudfront.net/service_vnf-6.4.0-1.20220509.qcow2
  type: OS
  dev_prefix: vd
  driver: qcow2
  size: 2147483648
  checksum:
    md5: 81ffd1f60c8f4860726ac712498daddd
    sha256: 5b2d33d98b20592a9750eda8ef78c0c976105d2d7048ef03d63d1ab23addc480
