---
name: OneKE 1.24 CE
version: 1.24.1-6.4.0-1.20220624
publisher: OpenNebula Systems
description: |-
  Beta release.

  Appliance with preinstalled OneKE 1.24 CE to work as a multi-master/multi-node cluster orchestrated by [OneFlow](https://docs.opennebula.io/6.4/management_and_operations/multivm_service_management/appflow_elasticity.html).

  Preconfigured with Canal CNI networking (Calico and Flannel) and MetalLB to handle load-balancing.

  Please refer to the [documentation](https://docs.opennebula.io/appliances/service/kubernetes_service.html).
short_description: Appliance with preinstalled OneKE 1.24 CE for KVM and vCenter hosts
tags:
- kubernetes
- service
- ubuntu
type: VMTEMPLATE
format: qcow2
creation_time: 1651140000
os-id: Ubuntu
os-release: "22.04 LTS"
os-arch: x86_64
hypervisor: ALL
opennebula_version: >-
  6.2, 6.3, 6.4
opennebula_template:
  context:
    grow_fs: "/"
    network: "YES"
    report_ready: "YES"
    token: "YES"
    oneapp_vrouter_eth0_vip0: "$ONEAPP_VROUTER_ETH0_VIP0"
    oneapp_vrouter_eth1_vip0: "$ONEAPP_VROUTER_ETH1_VIP0"
    oneapp_vnf_haproxy_lb2_port: "$ONEAPP_VNF_HAPROXY_LB2_PORT"
    oneapp_vnf_haproxy_lb3_port: "$ONEAPP_VNF_HAPROXY_LB3_PORT"
    oneapp_k8s_extra_sans: "$ONEAPP_K8S_EXTRA_SANS"
    oneapp_k8s_loadbalancer_config: "$ONEAPP_K8S_LOADBALANCER_CONFIG"
    oneapp_k8s_loadbalancer_range: "$ONEAPP_K8S_LOADBALANCER_RANGE"
    ssh_public_key: "$USER[SSH_PUBLIC_KEY]"
  cpu: "2"
  vcpu: "2"
  graphics:
    listen: "0.0.0.0"
    type: vnc
  inputs_order: ""
  memory: "3072"
  os:
    arch: x86_64
  user_inputs: {}
logo: kubernetes.png
disks:
- "OneKE 1.24 CE OS disk"
