---
name: Kubernetes 1.23 - KVM
version: 1.23.6-6.2.0-1.20220428
publisher: OpenNebula Systems
description: |-
  Beta release.

  Appliance with preinstalled Kubernetes/Ubuntu to work as a multi-master/multi-node cluster as OpenNebula OneFlow Service.

  Preconfigured with Canal CNI networking (Calico and Flannel) and MetalLB for load-balancing.
short_description: Appliance with preinstalled Kubernetes/Ubuntu for KVM hosts
tags:
- kubernetes
- service
- ubuntu
type: VMTEMPLATE
format: qcow2
creation_time: 1651140000
os-id: Ubuntu
os-release: "20.04.4 LTS"
os-arch: x86_64
hypervisor: KVM
opennebula_version: >-
  6.2, 6.3, 6.4
opennebula_template:
  sched_requirements: HYPERVISOR=kvm
  context:
    grow_fs: "/"
    network: "YES"
    report_ready: "YES"
    token: "YES"
    oneapp_k8s_control_plane_ep: "$ONEAPP_VNF_LB0_IP"
    oneapp_k8s_pods_network: "$ONEAPP_K8S_PODS_NETWORK"
    oneapp_k8s_port: "$ONEAPP_K8S_PORT"
    oneapp_k8s_loadbalancer_config: "$ONEAPP_K8S_LOADBALANCER_CONFIG"
    oneapp_k8s_loadbalancer_range: "$ONEAPP_K8S_LOADBALANCER_RANGE"
    ssh_public_key: "$USER[SSH_PUBLIC_KEY]"
  cpu: "2"
  vcpu: "2"
  graphics:
    listen: "0.0.0.0"
    type: vnc
  inputs_order: ""
  memory: "3072"
  os:
    arch: x86_64
  user_inputs: {}
logo: kubernetes.png
disks:
- "Kubernetes 1.23 OS disk - KVM"
